[book]
authors = ["Innes Anderson-Morrison"]
language = "en"
src = "src"
title = "The Penrose Book"

[output.html]
default-theme = "ayu"
edit-url-template = "https://github.com/sminez/penrose/edit/develop/docs/{path}"
